### ISSUE TITLE
General UX suggestion on audio

### ISSUE THREAD

**Issue by Rubinhuang9239** [greggman/vertexshaderart#11]
Sorry I did not find any place to leave suggestion so I end up giving this suggestion in the issue.

A small suggestion to the audio player in the www.vertexshaderart.com
Some of the sketches on the site contain audio from URLs like Sound Cloud.
When I try to leave the page, I use the browser's `go back` button normally, the audio seems not paused.
I do not know if this is intentional but I feel it's a bit annoy sometimes.
I appreciate your work and enjoying it!

**Comment by greggman** [comment]
Sorry but yes that is intentional. I found it annoying the other way to have sound start and stop and start an stop as I browsed.

When you click back there should be a pause button in the top left if you want to stop the music.

**Comment by Rubinhuang9239** [comment]
OK, never mind. Yeah I can use that pause. Thanks. @greggman
