### ISSUE TITLE
Can't set Profile image when using direct login.

### ISSUE THREAD

**Issue by Paul-JanPauptit** [greggman/vertexshaderart#2]
Which is not much of a problem, but the fact that the profile image now displays a broken image is visually unpleasant :)

**Comment by greggman** [comment]
If you signed up with email it's using [gravatar](http://gravatar.com/) for images

**Comment by Paul-JanPauptit** [comment]
Ah, it does look good now. Thanks for responding!

Closing the issue, assuming it was a temporary glitch. It was my first session after signing up, but I'm pretending that's not related :)
