### ISSUE TITLE
floatSound usage?

### ISSUE THREAD

**Issue by MV10** [greggman/vertexshaderart#20]
The WebAudio-derived `floatSound` texture should be zero-crossing PCM encoding, right? I'm familiar with PCM from OpenAL, but that's just arrays of `short` integers. Theoretically -32767 to +32767, but in practice it's maybe -2000 to 2000, at least on my system via Spotify through a loopback driver (I haven't had any success figuring out what controls the range of amplitude representation used by OpenAL).

I'm having trouble figuring out how to use it, and I've gone through a pretty large percentage of the available shaders, but only found a single example ([this](https://www.vertexshaderart.com/art/NpnhMDf6aivDMB3x9) and a few minor variations) that uses `floatSound`. Wondering if you might have some pointers to explain what to expect there.

Based on my OpenAL capture data, even if I try to focus on a very narrow range of possible values around zero, I get nothing out of the texture. In the example I linked, if I comment out the texture reference, I find that variable has to be relatively huge (compared to typical GL normalized ranges) like 60 to have any visible effects.

**Comment by greggman** [comment]
this is just the data from the web audio AnalyserNode

https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getFloatFrequencyData

I don't think many things on this site use it

**Comment by greggman** [comment]
Here's a sample:

https://www.vertexshaderart.com/art/sgg5X7iFw5d2SLzwX


You can see `floatSound` and `sound` are the same data except floatSound has more resolution (since `sound` [is based on 8bit values](https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/getByteFrequencyData)

Volume is a single value. It is not per frequency. ... though it does have a 240 frame history (volumn over time)

It is computed using the root mean square method which is a really bad method but I know next to nothing about audio so I have no clue how to compute a more perceptually correct volume.

**Comment by MV10** [comment]
Thanks. 

That sample is mine, actually... one of the "explainers" I was trying to write for my wife but `floatSound` doesn't work, so here we are. Edit: Oh I see, you modified it, cool. Thank you.

Haha, I'm the same way with audio, I was hoping The Great GMan would have new secrets to reveal. I'm actually writing some viz apps for my Raspberry Pi, which lacks the oomph to both stream audio and run webGL, but can handle this stuff in dedicated code. I settled on RMS as "volume" for now, too. That also means I'm going to have to figure out all the FFT stuff used for the `sound` texture (which, again, not really an audio guy, but hey, how hard can it be?)

**Comment by greggman** [comment]
That link I sent is not your sample. It's modified.

If `floatSound` is not working for you then it's likely your device doesn't support floating point textures

If you open the JavaScript console it will print some info. On my machines it prints

```
can use floating point textures
can render to floating point textures
can filter floating point textures
```

**Comment by MV10** [comment]
Yeah I noticed later you'd modified it. It does work and I do see those messages, thank you!

I noticed in your code you were speculating about using a shader to generate the uniform textures -- I was just pondering the same thing.

**Comment by MV10** [comment]
Oops, thought I closed this. One more audio question, if you don't mind -- for `sound` and `floatSound` how many actual data points are you writing into the texture? I thought I read somewhere it was 1024, or maybe I backtracked that in the code, and I know it sort of doesn't matter given the sampler spreads that 0.0 to 1.0, but just curious. I know Shadertoy uses 512.

Thanks again.

**Comment by greggman** [comment]
I'm writing whatever the `AnalyserNode` reports for `fequencyBinCount`

https://developer.mozilla.org/en-US/docs/Web/API/AnalyserNode/frequencyBinCount

https://github.com/greggman/vertexshaderart/blob/fa9fd45af8e5ec102ba7472357f0bb170f6aad9d/src/js/main.js#L638C1-L640C1

**Comment by MV10** [comment]
Gotcha. Thanks!
