### ISSUE TITLE
Line width

### ISSUE THREAD

**Issue by johanberonius** [greggman/vertexshaderart#4]
It would be nice to be able to set line width, just like point size, to draw thicker lines.

I can see that `gl.lineWidth` follows `window.devicePixelRatio` when `CSS` is selected. When I zoom in with `cmd`/`ctrl` + `+` DPR increases and so does the line width.

Is it possible to return a line width per vertex or at least set it globally?

Maybe the easiest is to add a few options to `Navitve`/`CSS` called `2x`, `3x`, `4x` to get the same effect as a higher DPR on all screens.

**Comment by greggman** [comment]
line width is no longer a feature of webgl.


Browsers needed to switch to the OpenGL 4+ core profile to support WebGL2 and the OpenGL 4+ core profile does not support line widths greater than 1. From the OpenGL 4.0+ spec, section E.2.1

> ## E.2.1 Deprecated But Still Supported Features

> The following features are deprecated, but still present in the core profile. They may be removed from a future version of OpenGL, and are removed in a forward compatible context implementing the core profile.

> * Wide lines - LineWidth values greater than 1.0 will generate an INVALID_VALUE error.
