### ISSUE TITLE
Api for get shader content ?

### ISSUE THREAD

**Issue by aiekick** [greggman/vertexshaderart#8]
Hello, 

i dev a free offline shader editor, and i would like to know if there a way to get the vertex and fragment from the url of vertexshaderart. 

at this moment i support shadertoy and glslsandbox, and i would like to support vertexshaderart. i have analysed your repo, but im no familiar with meteor :) 

thanks for your help :)

**Comment by greggman** [comment]
what do you want to know?

The core code runs without meteor as mentioned in the readme

**Comment by movAX13h** [comment]
I think he means if it is possible to get the shaders via https url instead of websocket connection so he can paste the shader urls into his application and load the shaders there.

**Comment by aiekick** [comment]
ok, not really understood :)

i would like to know if there is a url where i can get for shader, a json or other thing who containt the vertex shader code :)

**Comment by aiekick** [comment]
yep like you said  @movAX13h :)

**Comment by aiekick** [comment]
by example, if i have this rul : https://www.vertexshaderart.com/art/mNBny7JXpBGwQnMwG

So i thinck, the id is mNBny7JXpBGwQnMwG. so what url i can have to get a json or a structure to get the vertex shader of this id ? 

thanks for your help :)

**Comment by greggman** [comment]
There isn't a way to do that currently 😓

**Comment by aiekick** [comment]
arf :)

**Comment by greggman** [comment]
Try adding `?format=json` to the URL. Only works for shaders not every page

Example:

https://www.vertexshaderart.com/art/LPS8BeAeCDomFZXzX?format=json

**Comment by aiekick** [comment]
nice, thanks for that. im not sure i understand what you say with "Only works for shaders not every page".

there is some shader where this url style not work ? myabe its just my bad english ( im french :) )

**Comment by aiekick** [comment]
maybe the format is partially wrong, here the json form your url 👍 

`{
	"_id": "LPS8BeAeCDomFZXzX",
	"createdAt": "2017-11-28T18:41:16.304Z",
	"modifiedAt": "2017-11-28T19:14:21.200Z",
	"origId": "qtwQmSqQKkS3ptSYN",
	"name": "omg",
	"username": "gman",
	"avatarUrl": "https://secure.gravatar.com/avatar/dcc0309895c3d6db087631813efaa9d1?default=retro&size=200",
	"settings": 
        "{\"num\":14909,\"mode\":\"TRIANGLES\",\"sound\":\"https://soundcloud.com/dirtybirdrecords/claudevonstroke-dood\",,\"lineSize\":\"NATIVE\",\"backgroundColor\":[1,1,1,1],\"shader\":\"/*\\n\\nðŸ”´\\n\\n*/\\n\\n\\n`

After settings, you have some "{\ " and other \ " outside the shader code, you have also \ \ n 
i think you can remove some \ " and let the " and replace the \ \ by just the \

**Comment by greggman** [comment]
As it says in the README the editor/visualizer and the site are 2 different apps. So the site just stores the visualizer's data as a string. 

```
const xhr = new XMLHttpRequest();
xhr.addEventListener('load', function() {
  const art = JSON.parse(this.responseText);
  const settings = JSON.parse(art.settings);
  
  // inspect this in the JavaScript console
  console.log(settings);
});
xhr.open("GET", "https://www.vertexshaderart.com/art/zd2E5vCZduc5JeoFz?format=json");
xhr.send();
```

Here's the [visualizer running on it's own](https://rawgit.com/greggman/vertexshaderart/master/src/index.html)

**Comment by aiekick** [comment]
ok so its perfect for me, i just want the code of the sahder with the parameteres you use for load the shader. thanks. by the way can you correct a little bit the json format ? thanks

**Comment by greggman** [comment]
I'm not sure what you mean by "correct the json". Do you have an example where the code I provided above doesn't work?

**Comment by aiekick** [comment]
i shared detail on top in my post. 

after settings in your json you have this : "{\"num\":14909, so the { of the json is included between quotes. and after that you have many \ \ n and many \ " who are useless and breack the json format

if you replace all \ \ n by \ n, all \ \ t by \ t , all "{ by { and all }" by } it will be ok :)
 
you can test your json here : https://jsonformatter.curiousconcept.com/

by example here, the json generated by shadertoy : 
https://www.shadertoy.com/api/v1/shaders/MllBDN?key=NtnKwr

i can correct your json myself during the import process in my soft. no problem, but its better if you do the fix yourself :) by the way thanks for this feature :)

**Comment by aiekick** [comment]
ok ti works, in fact you use another json format in settings. its weird to insert a json string into another json string, but ok it work :)

**Comment by greggman** [comment]
it's not a poor format. Its separation of concerns. The website doesn't know the format of the visualiser. It could be xml, CSV, yaml, whatever. it just stores the data from the visualiser and passes it back

**Comment by aiekick** [comment]
ok ok. i know what is the principle of the MVC :)

**Comment by greggman** [comment]
Thinking about it more I think you are right. Internally it's storing the visualizer data as an opaque chunk of data but I can see how the URL above should return just JSON.

I'll fix it.

**Comment by greggman** [comment]
Fixed

**Comment by aiekick** [comment]
thanks
