### ISSUE TITLE
Domain Unreashable ?

### ISSUE THREAD

**Issue by aiekick** [greggman/vertexshaderart#9]
Since 4-5 days, the domain is unreashable ? is there a problem ?

**Comment by greggman** [comment]
Yes, the site is down. I don't know if someone hacked it or what. Getting it back up is taking longer than I expected. Hopefully it won't be too much longer.

**Comment by greggman** [comment]
It might be up now. no idea what took it down before. If the same thing happens then um, ugh.

If it was a hacker it would be nice if they'd instead come where and help secure it 😅

**Comment by aiekick** [comment]
yep, sure :) thanks :)
